name: Chrome tests

on:
  push
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 6,14,22 * * *'


jobs:
  sudo sed -i.bak 's/updates/extra updates/' /etc/depmod.d/ubuntu.conf
  sudo depmod
  sudo modprobe zfs
  # Workaround to provide additional free space for testing.
  #   https://github.com/actions/virtual-environments/issues/2840
  sudo rm -rf /usr/share/dotnet
  sudo rm -rf /opt/ghc
  sudo rm -rf "/usr/local/share/boost"
  sudo rm -rf "$AGENT_TOOLSDIRECTORY"



  
                
